# Generated by Django 5.1.2 on 2024-12-11 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='marca',
            new_name='nome',
        ),
    ]
